services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        TURBO_TEAM: ${TURBO_TEAM}
        TURBO_TOKEN: ${TURBO_TOKEN}
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      start_period: 5s
      retries: 3

networks:
  app_network:
    name: app_network
    external: true
